version: '3.5'

services: 
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym-tracker
    ports:
     - '3000:3000'
    volumes:
     - .:/app
     - /app/node_modules

volumes:
 postgres-data: